/**
 * GET    /api/wordpress/sites          — list every WP site the user has connected
 * POST   /api/wordpress/sites          — add a new site (Pro-gated, max 5)
 *
 * Per-site PATCH (relabel / set default) + DELETE live at
 * /api/wordpress/sites/[id]/route.ts. Splitting them keeps each route file
 * narrow and the URL semantics RESTful.
 *
 * All routes scope by auth.uid() via RLS; we ALSO pass user.id explicitly so
 * the helpers can do tier-gating math without re-fetching the user.
 */
import { NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase/server'
import {
  listSites,
  addSite,
  canAddSite,
} from '@/lib/wordpress-sites'
import { normalizeTier } from '@/lib/tier'
import { getAuthAndOwner } from '@/lib/agency-auth'

export async function GET() {
  const supabase = await createServerClient()
  // 2026-06-09 Phase 2 (VA): WP sites list + cap belongs to the owner —
  // sites are the owner's, not the VA's.
  const auth = await getAuthAndOwner(supabase)
  if (auth.error) return auth.error
  const { ownerId } = auth

  // Tier + current cap usage so the UI can render "3 of 5 sites" and
  // gate the "+ Add another" button without a second round trip.
  const { data: integ } = await supabase
    .from('integrations')
    .select('tier')
    .eq('user_id', ownerId)
    .maybeSingle()
  const tier = normalizeTier(integ?.tier)
  const sites = await listSites(supabase, ownerId)
  const cap = await canAddSite(supabase, ownerId, tier)

  return NextResponse.json({
    sites,
    cap: {
      current: cap.current,
      max: cap.cap,
      canAddMore: cap.allowed,
    },
    tier,
  })
}

/**
 * Decode a Connection Token generated by the MVP Affiliate plugin.
 * Mirrors the logic in /api/wordpress/connect-token/route.ts — base64url
 * encoded JSON of { url, username, password, version }. Kept inline here
 * (not extracted) because the multi-site path adds tier-gating + a
 * different storage target (wordpress_sites table, not the legacy
 * integrations columns), so it doesn't share enough with connect-token
 * to justify a shared helper yet.
 */
function decodeConnectionToken(raw: string): { url: string; username: string; password: string } | null {
  try {
    let b64 = raw.trim().replace(/-/g, '+').replace(/_/g, '/')
    while (b64.length % 4) b64 += '='
    const json = Buffer.from(b64, 'base64').toString('utf8')
    const obj = JSON.parse(json) as { url?: string; username?: string; password?: string }
    if (!obj.url || !obj.username || !obj.password) return null
    return { url: obj.url, username: obj.username, password: obj.password }
  } catch {
    return null
  }
}

export async function POST(req: Request) {
  const supabase = await createServerClient()
  const auth = await getAuthAndOwner(supabase)
  if (auth.error) return auth.error
  const { ownerId } = auth

  const body = await req.json().catch(() => ({})) as {
    label?: string
    url?: string
    username?: string
    appPassword?: string
    apiToken?: string
    /** Optional one-liner from the MVP Affiliate plugin's "Generate
     *  Connection Token" button. If present, we decode it and use the
     *  embedded url/username/password — bypasses the manual Application
     *  Password dance. Mutually exclusive with url+username+appPassword;
     *  if both are sent, the token wins. */
    token?: string
    /** Onboarding path 2: create the site in content-only "bring your own
     *  theme" mode, with the chosen CTA style. Default = full MVP treatment. */
    contentOnly?: boolean
    ctaStyle?: 'button' | 'link'
  }

  // Token path — decode and overlay onto the rest of the body so the
  // validation + storage path stays single-flow.
  if (body.token && typeof body.token === 'string') {
    const decoded = decodeConnectionToken(body.token)
    if (!decoded) {
      return NextResponse.json({
        error: 'That token doesn\'t look right. Open MVP Affiliate in your wp-admin, click Generate Connection Token, and paste the full token here.',
      }, { status: 400 })
    }
    // Normalize URL the same way connect-token does so this path
    // behaves identically to the single-site flow.
    let siteUrl = decoded.url.trim().replace(/\/$/, '')
    if (!siteUrl.startsWith('http')) siteUrl = `https://${siteUrl}`
    body.url = siteUrl
    body.username = decoded.username.trim()
    body.appPassword = decoded.password.replace(/\s+/g, '')
  }

  // Basic input validation. The DB CHECK trigger + RLS handle the rest.
  if (!body.url || !body.username || !body.appPassword) {
    return NextResponse.json(
      { error: 'url, username and appPassword are all required (or send a token).' },
      { status: 400 },
    )
  }
  try {
    new URL(body.url)
  } catch {
    return NextResponse.json({ error: 'Please enter a full URL (https://your-site.com).' }, { status: 400 })
  }

  const { data: integ } = await supabase
    .from('integrations')
    .select('tier')
    .eq('user_id', ownerId)
    .maybeSingle()
  const tier = normalizeTier(integ?.tier)

  const result = await addSite(supabase, ownerId, tier, {
    label: body.label || '',
    url: body.url,
    username: body.username,
    appPassword: body.appPassword,
    apiToken: body.apiToken || null,
    contentOnly: body.contentOnly === true,
    ctaStyle: body.ctaStyle === 'link' ? 'link' : 'button',
  })
  if (!result.ok) {
    // 402 for "upgrade required" so the UI can detect tier-gated errors
    // separately from 400 input errors and surface an upgrade CTA.
    const status = result.error.toLowerCase().includes('pro') ? 402 : 400
    return NextResponse.json({ error: result.error }, { status })
  }

  return NextResponse.json({ ok: true, site: result.site })
}
