/**
 * Connect WordPress via a one-line token generated by the MVP Affiliate plugin.
 *
 * The token is base64url-encoded JSON of { url, username, password, version }.
 * We decode, verify Basic Auth works against /wp-json/wp/v2/users/me, store
 * credentials, then run the post-connect setup (clear default content, install
 * theme/plugins via plugin if needed, etc.) — same as connect-and-setup but
 * without the manual credential dance.
 */

import { NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase/server'
import { maybeEncrypt } from '@/lib/secrets'

export const maxDuration = 60

interface TokenPayload {
  url: string
  username: string
  password: string
  version?: string
}

function decodeToken(raw: string): TokenPayload | null {
  try {
    // base64url → base64
    let b64 = raw.trim().replace(/-/g, '+').replace(/_/g, '/')
    while (b64.length % 4) b64 += '='
    const json = Buffer.from(b64, 'base64').toString('utf8')
    const obj = JSON.parse(json) as Partial<TokenPayload>
    if (!obj.url || !obj.username || !obj.password) return null
    return { url: obj.url, username: obj.username, password: obj.password, version: obj.version }
  } catch {
    return null
  }
}

export async function POST(request: Request) {
  try {
    const supabase = await createServerClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { token } = await request.json() as { token?: string }
    if (!token || typeof token !== 'string') {
      return NextResponse.json({ error: 'Connection token is required.' }, { status: 400 })
    }

    const payload = decodeToken(token)
    if (!payload) {
      return NextResponse.json({
        error: 'That token doesn\'t look right. Open MVP Affiliate in your wp-admin, click Generate Connection Token, and paste the full token here.',
      }, { status: 400 })
    }

    let siteUrl = payload.url.trim().replace(/\/$/, '')
    if (!siteUrl.startsWith('http')) siteUrl = `https://${siteUrl}`
    const username = payload.username.trim()
    const appPassword = payload.password.replace(/\s+/g, '')

    // Verify Basic Auth works against the live site
    const authHeader = `Basic ${Buffer.from(`${username}:${appPassword}`).toString('base64')}`
    let verifyRes: Response
    try {
      verifyRes = await fetch(`${siteUrl}/wp-json/wp/v2/users/me`, {
        headers: { Authorization: authHeader },
        signal: AbortSignal.timeout(10000),
      })
    } catch {
      return NextResponse.json({
        error: `Could not reach ${siteUrl}. Make sure your site is live and the URL in the token is correct.`,
      }, { status: 400 })
    }

    if (!verifyRes.ok) {
      const body = await verifyRes.text()
      return NextResponse.json({
        error: `WordPress rejected the token (${verifyRes.status}). Regenerate it from the MVP Affiliate menu in your wp-admin. ${body.slice(0, 120)}`,
      }, { status: 400 })
    }

    // Verify the AffiliateOS REST endpoint is reachable (plugin is active)
    try {
      const pingRes = await fetch(`${siteUrl}/wp-json/affiliateos/v1/customizations`, {
        headers: { Authorization: authHeader },
        signal: AbortSignal.timeout(8000),
      })
      if (pingRes.status === 404) {
        return NextResponse.json({
          error: 'The MVP Affiliate plugin isn\'t responding. Make sure it\'s activated in wp-admin → Plugins.',
        }, { status: 400 })
      }
    } catch { /* non-fatal — plugin endpoint may take a moment to register */ }

    // Save credentials
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await supabase.from('integrations').upsert(
      {
        user_id: user.id,
        wordpress_url: siteUrl,
        wordpress_username: username,
        // Encrypt at rest (2026-06-02 rollout). Reads go through
        // maybeDecrypt in lib/wordpress-sites.ts.
        wordpress_app_password: maybeEncrypt(appPassword),
        wordpress_api_token: maybeEncrypt(appPassword),
        setup_status: 'site_ready',
      },
      { onConflict: 'user_id' },
    )

    return NextResponse.json({ ok: true, siteUrl, username })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error('[connect-token] error:', msg)
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
