-- © 2026 Gominplanet / MVP Affiliate — proprietary & confidential.
--
-- WITHDRAWN. This migration created an index that already existed, and its only
-- job now is to remove the duplicate it made.
--
-- The original claim was that youtube_videos had no index serving the app's
-- hottest read, "this creator's videos, newest first". That was wrong. The
-- database already had:
--
--   idx_youtube_videos_user_published  on (user_id, published_at DESC)
--
-- It is not in any migration file. It was created directly in Supabase, and its
-- naming gives it away: every index in this folder is named <thing>_idx, and
-- that one uses the idx_<thing> convention instead.
--
-- The lesson is the one that keeps coming back in this codebase. The migrations
-- folder is a record of what we asked for, not a description of what is in the
-- database, and only the database can answer the second question. `npm run
-- schema:audit` prints the query for exactly this reason. A grep over these
-- files is evidence of intent, and intent is not the artifact.
--
-- Two identical indexes are not harmless: every insert and update to
-- youtube_videos maintains both, and the second buys nothing. So this drops the
-- one this migration added and leaves the original alone.
--
-- Safe to run twice.

drop index if exists public.youtube_videos_user_published_idx;
