/**
 * POST /api/blog/instagram-post
 *
 * Publishes a review to the user's Instagram. Two flavors:
 *
 *   kind = 'video' (default): vertical 9:16 MP4 the user uploaded.
 *     mode = 'reel' | 'story' | 'both'
 *
 *   kind = 'image': 4:5 composed image generated from the YouTube thumbnail
 *     (auto-generated by /api/instagram/compose-thumbnail-image).
 *     mode = 'image' | 'story' | 'both'
 *
 * Tier: Pro-only.
 */
import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase/server'
import { resolveBlogPostId } from '@/lib/resolve-post-id'
import { createAnthropicClient } from '@/lib/anthropic'
import { publishMedia, refreshLongLivedToken } from '@/services/instagram'
import { cloudinaryConfigured, overlayCaptionOnVideo } from '@/services/cloudinary'
import { createGeniuslinkService } from '@/services/geniuslink'
import { tierAllowsSocial, type Tier } from '@/lib/tier'
import { learnProfileToPrompt } from '@/lib/learn'
import { recordAnthropicUsage } from '@/lib/ai-usage'
import { readSocialCount, incrementSocialCount, evaluateSocialCap, SOCIAL_CAP } from '@/lib/social-cap'
import { resolveSocialAccount } from '@/lib/social-accounts'
import { metaEnabledForUser } from '@/lib/feature-flags'

const ASIN_RE = /\b([A-Z0-9]{10})\b/

export const maxDuration = 300

const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000

type VideoMode = 'reel' | 'story' | 'both'
type ImageMode = 'image' | 'story' | 'both'

export async function POST(request: NextRequest) {
  try {
    const supabase = await createServerClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    if (!(await metaEnabledForUser(supabase, user))) return NextResponse.json({ error: 'Instagram publishing is temporarily unavailable while our Meta integration is under review.' }, { status: 503 })

    const body = await request.json() as {
      postId?: string
      postUrl?: string
      kind?: 'video' | 'image'
      mode?: string
      dryRun?: boolean
      caption?: string
      socialAccountId?: string
    }
    // Resolve video-less rows' WP post id → blog_posts UUID, like every other
    // social-post route — future-proofs IG when wired into OrphanPostShare.
    const postId = (await resolveBlogPostId(supabase, user.id, body.postId, body.postUrl)) || body.postId
    const kind = body.kind === 'image' ? 'image' : 'video'
    const mode = body.mode ?? (kind === 'image' ? 'image' : 'reel')
    const dryRun = body.dryRun === true
    const overrideCaption = body.caption
    if (!postId) return NextResponse.json({ error: 'postId required' }, { status: 400 })

    const validModes = kind === 'image' ? ['image', 'story', 'both'] : ['reel', 'story', 'both']
    if (!validModes.includes(mode)) {
      return NextResponse.json({ error: `mode must be one of ${validModes.join(' | ')} for kind=${kind}` }, { status: 400 })
    }

    // ── Tier gate + integration fetch ───────────────────────────────────────
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: intRow } = await supabase
      .from('integrations')
      .select('tier,instagram_user_id,instagram_access_token,instagram_token_expiry,instagram_username,geniuslink_api_key,geniuslink_api_secret,amazon_associates_tag')
      .eq('user_id', user.id)
      .single()
    const tier = (intRow?.tier as Tier) ?? 'trial'
    if (!tierAllowsSocial(tier, 'instagram')) {
      return NextResponse.json(
        { error: 'Instagram auto-publish is a Pro plan feature. Upgrade to Pro to post to Instagram.' },
        { status: 403 },
      )
    }
    // Resolve WHICH Instagram account to post to. IG is Pro-only (gated
    // above), so selection is always allowed here. Falls back to the legacy
    // integrations columns when social_accounts is empty.
    const igAccount = await resolveSocialAccount(supabase, user.id, 'instagram', {
      socialAccountId: body.socialAccountId,
      allowSelection: true,
      legacy: {
        externalId: intRow?.instagram_user_id,
        accessToken: intRow?.instagram_access_token,
        displayName: intRow?.instagram_username,
      },
    })
    if (!igAccount) {
      return NextResponse.json({ error: 'Instagram not connected. Visit Setup → Integrations to connect your Instagram account.' }, { status: 400 })
    }
    const igUserId = igAccount.externalId
    let igToken = igAccount.accessToken

    // Token-expiry refresh only applies to the legacy/default account — that's
    // the one whose expiry we track on `integrations`. (IG is single-account
    // in practice today; a selected non-default account skips this.)
    const isLegacyDefault = !igAccount.id || igAccount.externalId === (intRow?.instagram_user_id as string | null)
    const tokenExpiry = intRow?.instagram_token_expiry as number | null
    if (!dryRun && isLegacyDefault && tokenExpiry && tokenExpiry - Date.now() < SEVEN_DAYS_MS) {
      try {
        const refreshed = await refreshLongLivedToken(igToken)
        igToken = refreshed.accessToken
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await supabase
          .from('integrations')
          .update({ instagram_access_token: refreshed.accessToken, instagram_token_expiry: refreshed.expiresAt })
          .eq('user_id', user.id)
        // Keep the mirrored social_accounts row's token fresh too.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await supabase
          .from('social_accounts')
          .update({ access_token: refreshed.accessToken, updated_at: new Date().toISOString() })
          .eq('user_id', user.id).eq('platform', 'instagram').eq('external_id', igUserId)
      } catch { /* fall through with existing token */ }
    }

    // ── Fetch post + linked video ───────────────────────────────────────────
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: postRow } = await supabase
      .from('blog_posts')
      .select('id,title,excerpt,content,wordpress_url,video_id,social_publish_counts,youtube_videos(instagram_video_url,instagram_image_url,instagram_story_image_url,thumbnail_url,title)')
      .eq('id', postId)
      .eq('user_id', user.id)
      .single()
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const post = postRow as any
    if (!post) return NextResponse.json({ error: 'Post not found' }, { status: 404 })

    const igSocialCount = readSocialCount(post, 'instagram')
    const igCap = evaluateSocialCap(igSocialCount)
    if (!dryRun && igCap.exceeded) {
      return NextResponse.json({
        error: `You've published this post to Instagram ${SOCIAL_CAP} times — that's the per-post cap on re-publishing. Edit the post or use a different post.`,
        socialCapReached: true,
        platform: 'instagram',
      }, { status: 429 })
    }

    const videoUrl = post.youtube_videos?.instagram_video_url as string | null
    const imageUrl = post.youtube_videos?.instagram_image_url as string | null
    // 9:16 variant for Stories. Falls back to the 4:5 feed image for rows
    // composed before migration 018 (Instagram will zoom-crop it).
    const storyImageUrl = (post.youtube_videos?.instagram_story_image_url as string | null) || imageUrl

    if (!dryRun) {
      if (kind === 'video' && !videoUrl) {
        return NextResponse.json(
          { error: 'No vertical Instagram video uploaded. Open the post in YouTube Co-Pilot and upload a 9:16 MP4 first.' },
          { status: 400 },
        )
      }
      if (kind === 'image' && !imageUrl) {
        return NextResponse.json(
          { error: 'No Instagram image composed yet. Generate the image first via /api/instagram/compose-thumbnail-image.' },
          { status: 400 },
        )
      }
    }

    // Compute the affiliate URL (used in Story link-sticker prompt)
    let affiliateUrl = (post.wordpress_url as string | null) || ''
    const ytTitle = post.youtube_videos?.title as string | undefined
    const asinMatch = ytTitle ? ytTitle.match(ASIN_RE) : null
    if (asinMatch) {
      const asin = asinMatch[1]
      if (intRow?.geniuslink_api_key && intRow?.geniuslink_api_secret) {
        try {
          const genius = createGeniuslinkService(intRow.geniuslink_api_key, intRow.geniuslink_api_secret)
          affiliateUrl = await genius.createAsinLink(asin, post.title || asin)
        } catch {
          affiliateUrl = `https://www.amazon.com/dp/${asin}${intRow?.amazon_associates_tag ? `?tag=${intRow.amazon_associates_tag}` : ''}`
        }
      } else {
        affiliateUrl = `https://www.amazon.com/dp/${asin}${intRow?.amazon_associates_tag ? `?tag=${intRow.amazon_associates_tag}` : ''}`
      }
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: brandRow } = await supabase
      .from('brand_profiles')
      .select('name,voice_summary,learn_profile')
      .eq('user_id', user.id)
      .single()
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const brand = brandRow as any
    const voiceNote = brand?.voice_summary ? `\n\nVoice guidance: ${brand.voice_summary}` : ''
    const learnBlock = learnProfileToPrompt(brand?.learn_profile)

    const results: {
      reelId?: string
      imagePostId?: string
      storyId?: string
      affiliateUrl?: string
      reelCaption?: string
      warnings: string[]
    } = { warnings: [] }

    // ── Build the feed caption (used by Reel OR Image-post) ─────────────────
    const wantsFeedCaption =
      (kind === 'video' && (mode === 'reel' || mode === 'both')) ||
      (kind === 'image' && (mode === 'image' || mode === 'both'))

    let feedCaption: string | null = null
    if (wantsFeedCaption) {
      if (overrideCaption && overrideCaption.trim()) {
        feedCaption = overrideCaption.replace(/https?:\/\/\S+/g, '').trim()
        if (feedCaption.length > 2200) feedCaption = feedCaption.slice(0, 2199) + '…'
      } else {
        const plainContent = (post.content as string ?? '').replace(/<[^>]+>/g, '').slice(0, 1500)
        const anthropic = createAnthropicClient()
        const postTypeLabel = kind === 'image' ? 'IMAGE FEED POST' : 'REEL'
        const msg = await anthropic.messages.create({
          model: 'claude-haiku-4-5-20251001',
          max_tokens: 700,
          messages: [{
            role: 'user',
            content: `Write an Instagram ${postTypeLabel} caption for this product review article.

Style: a content creator's authentic, punchy take. Strong hook in line 1 (max 6 words). 2-3 short value lines below the hook. End with 15-25 hashtags optimized for Instagram SEO — mix of broad high-traffic + niche-specific + product/brand. Match the voice provided.${voiceNote}${learnBlock ? `\n\n${learnBlock}` : ''}

Hard rules:
- TOTAL output (text + hashtags) must be under 2000 characters.
- Do NOT include any URL — URLs are not clickable in Instagram captions and look unprofessional.
- Plain text only. NO markdown formatting (no **, no _, no [text](link)).
- One emoji at the start of the hook is welcome. Don't pile them on.
- Hashtags go on the last line(s), each prefixed with #, lowercase, no spaces inside the tag.

Blog title: ${post.title}
Blog excerpt: ${post.excerpt || plainContent.slice(0, 300)}
Content preview: ${plainContent}

Return ONLY the caption text + hashtags.`,
          }],
        })
        feedCaption = ((msg.content[0] as { type: string; text: string }).text || '').trim()
        feedCaption = feedCaption.replace(/https?:\/\/\S+/g, '').trim()
        recordAnthropicUsage(msg, {
          userId: user.id, tier,
          feature: 'social_instagram_caption', model: 'claude-haiku-4-5-20251001',
        })
        if (feedCaption.length > 2200) feedCaption = feedCaption.slice(0, 2199) + '…'
      }
      // Reel/feed captions can't carry a clickable URL, so direct people to the
      // bio link — the standard creator CTA. Appended above any hashtag block.
      if (feedCaption) {
        const linkLine = '👆 Link in bio'
        if (!/link in bio/i.test(feedCaption)) {
          // Insert before the trailing hashtag line(s) so it reads naturally.
          const lines = feedCaption.split('\n')
          let firstTagIdx = lines.findIndex(l => /^\s*#/.test(l))
          if (firstTagIdx === -1) firstTagIdx = lines.length
          lines.splice(firstTagIdx, 0, '', linkLine, '')
          feedCaption = lines.join('\n').replace(/\n{3,}/g, '\n\n').trim()
          if (feedCaption.length > 2200) feedCaption = feedCaption.slice(0, 2199) + '…'
        }
      }
    }

    if (dryRun) {
      return NextResponse.json({
        ok: true,
        dryRun: true,
        reelCaption: feedCaption ?? null, // legacy field name — UI reads this
        affiliateUrl: (mode === 'story' || mode === 'both') ? affiliateUrl : null,
      })
    }

    // ── Publish: video kind ─────────────────────────────────────────────────
    if (kind === 'video') {
      const m = mode as VideoMode
      // Burn a "LINK IN BIO" caption into the lower third of the video (Reels
      // can't carry a clickable link). Falls back to the original video if
      // Cloudinary isn't configured or the overlay fails.
      let effectiveVideoUrl = videoUrl as string
      if (cloudinaryConfigured() && effectiveVideoUrl) {
        const overlaid = await overlayCaptionOnVideo(effectiveVideoUrl, 'LINK IN BIO')
        if (overlaid?.url) effectiveVideoUrl = overlaid.url
        else results.warnings.push('Could not burn the on-screen caption — posted the original video.')
      }
      if (m === 'reel' || m === 'both') {
        try {
          const reelId = await publishMedia({
            userId: igUserId,
            accessToken: igToken,
            mediaType: 'REELS',
            videoUrl: effectiveVideoUrl,
            caption: feedCaption ?? '',
            shareToFeed: true,
          })
          results.reelId = reelId
          results.reelCaption = feedCaption ?? undefined
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          await supabase.from('blog_posts').update({ instagram_reel_id: reelId }).eq('id', postId)
        } catch (err) {
          results.warnings.push(`Reel publish failed: ${err instanceof Error ? err.message : String(err)}`)
        }
      }
      if (m === 'story' || m === 'both') {
        try {
          const storyId = await publishMedia({
            userId: igUserId,
            accessToken: igToken,
            mediaType: 'STORIES',
            videoUrl: effectiveVideoUrl,
          })
          results.storyId = storyId
          results.affiliateUrl = affiliateUrl
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          await supabase.from('blog_posts').update({ instagram_story_id: storyId }).eq('id', postId)
        } catch (err) {
          results.warnings.push(`Story publish failed: ${err instanceof Error ? err.message : String(err)}`)
        }
      }
    }

    // ── Publish: image kind ─────────────────────────────────────────────────
    if (kind === 'image') {
      const m = mode as ImageMode
      if (m === 'image' || m === 'both') {
        try {
          const imagePostId = await publishMedia({
            userId: igUserId,
            accessToken: igToken,
            mediaType: 'IMAGE',
            imageUrl: imageUrl as string,
            caption: feedCaption ?? '',
          })
          results.imagePostId = imagePostId
          results.reelCaption = feedCaption ?? undefined
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          await supabase.from('blog_posts').update({ instagram_image_post_id: imagePostId }).eq('id', postId)
        } catch (err) {
          results.warnings.push(`Image post publish failed: ${err instanceof Error ? err.message : String(err)}`)
        }
      }
      if (m === 'story' || m === 'both') {
        try {
          const storyId = await publishMedia({
            userId: igUserId,
            accessToken: igToken,
            mediaType: 'STORIES',
            imageUrl: storyImageUrl as string,
          })
          results.storyId = storyId
          results.affiliateUrl = affiliateUrl
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          await supabase.from('blog_posts').update({ instagram_story_id: storyId }).eq('id', postId)
        } catch (err) {
          results.warnings.push(`Story publish failed: ${err instanceof Error ? err.message : String(err)}`)
        }
      }
    }

    const anySuccess = results.reelId || results.storyId || results.imagePostId
    if (!anySuccess) {
      return NextResponse.json({ ok: false, ...results }, { status: 502 })
    }
    // Count one increment per successful publish session, regardless of
    // mode — Reel + Story together still = 1 use of the cap on this post.
    await incrementSocialCount(supabase, postId!, 'instagram')
    return NextResponse.json({
      ok: true,
      ...results,
      publishCount: igSocialCount + 1,
      isLastAllowed: igCap.willBeLast,
    })
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
